// <auto-generated />
using MenuApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuApp.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20240610105854_update links")]
    partial class updatelinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenuApp.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.arla.com/recordid/028FC826-276D-42A7-8E2E5E1E6F5F13B7/pizza-margherita-med-burrata.jpg?format=jpg&width=1200&height=630&mode=crop&crop=(0,1568,0,-54)",
                            Name = "Salatpizza",
                            Price = 10.99
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://www.allrecipes.com/thmb/XDFvpo7BXQ7_s920fAp28qox0PY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/279460-Old-Bay-Seafood-Boil-ddmfs-139-4x3-aa189a5c09104659957fe6fcb715c4bd.jpg",
                            Name = "Seafood Boil",
                            Price = 20.989999999999998
                        });
                });

            modelBuilder.Entity("MenuApp.Models.DishIngredient", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngredientId = 1
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 2
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 3
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 4
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 5
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 6
                        });
                });

            modelBuilder.Entity("MenuApp.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tomato Sauce"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kebab"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shrimp"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Crab"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Corn"
                        });
                });

            modelBuilder.Entity("MenuApp.Models.DishIngredient", b =>
                {
                    b.HasOne("MenuApp.Models.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuApp.Models.Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MenuApp.Models.Dish", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("MenuApp.Models.Ingredient", b =>
                {
                    b.Navigation("DishIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
